// TypeScript enum для AuditAction
export enum AuditActionEnum {
  USER_LOGIN = 'user_login',
  USER_LOGOUT = 'user_logout',
  USER_REGISTER = 'user_register',
  USER_UPDATE_PROFILE = 'user_update_profile',
  USER_CHANGE_PASSWORD = 'user_change_password',
  USER_DELETE_ACCOUNT = 'user_delete_account',
  ROLE_ASSIGNED = 'role_assigned',
  ROLE_REMOVED = 'role_removed',
  PERMISSION_GRANTED = 'permission_granted',
  PERMISSION_REVOKED = 'permission_revoked',
  NETWORK_CREATED = 'network_created',
  NETWORK_UPDATED = 'network_updated',
  NETWORK_DELETED = 'network_deleted',
  STORE_CREATED = 'store_created',
  STORE_UPDATED = 'store_updated',
  STORE_DELETED = 'store_deleted',
  BRAND_CREATED = 'brand_created',
  BRAND_UPDATED = 'brand_updated',
  BRAND_DELETED = 'brand_deleted',
  LOYALTY_CARD_CREATED = 'loyalty_card_created',
  LOYALTY_CARD_UPDATED = 'loyalty_card_updated',
  LOYALTY_CARD_DELETED = 'loyalty_card_deleted',
  PAYMENT_PROCESSED = 'payment_processed',
  REFUND_ISSUED = 'refund_issued',
  CAMPAIGN_CREATED = 'campaign_created',
  CAMPAIGN_UPDATED = 'campaign_updated',
  CAMPAIGN_DELETED = 'campaign_deleted',
  REPORT_GENERATED = 'report_generated',
  SYSTEM_SETTING_CHANGED = 'system_setting_changed',
  SUSPICIOUS_ACTIVITY_DETECTED = 'suspicious_activity_detected',
  ACCOUNT_LOCKED = 'account_locked',
  ACCOUNT_UNLOCKED = 'account_unlocked',
  API_KEY_CREATED = 'api_key_created',
  API_KEY_REVOKED = 'api_key_revoked',
}

// TypeScript enum для AuditStatus
export enum AuditStatusEnum {
  SUCCESS = 'success',
  FAILURE = 'failure',
  WARNING = 'warning',
  INFO = 'info',
}
