apiVersion: v1
kind: ConfigMap
metadata:
  name: salespot-config
  namespace: salespot
data:
  NODE_ENV: 'production'
  PORT: '3001'
  API_PREFIX: '/api/v1'
  CORS_ORIGIN: 'https://salespot.by'
  REDIS_HOST: 'salespot-redis'
  REDIS_PORT: '6379'
  KONG_ADMIN_URL: 'http://salespot-kong-admin:8001'
  CIRCUIT_BREAKER_TIMEOUT: '30000'
  CIRCUIT_BREAKER_ERROR_THRESHOLD: '5'
  CIRCUIT_BREAKER_RESET_TIMEOUT: '60000'
  CIRCUIT_BREAKER_VOLUME_THRESHOLD: '10'
  LOAD_BALANCER_HEALTH_CHECK_INTERVAL: '30000'
  LOAD_BALANCER_HEALTH_CHECK_TIMEOUT: '5000'
  LOAD_BALANCER_MAX_RETRIES: '3'
  SERVICE_DISCOVERY_HEARTBEAT_INTERVAL: '30000'
  SERVICE_DISCOVERY_HEARTBEAT_TIMEOUT: '10000'
  SERVICE_DISCOVERY_CLEANUP_INTERVAL: '60000'
  SERVICE_DISCOVERY_MAX_AGE: '300000'
