apiVersion: apps/v1
kind: Deployment
metadata:
  name: salespot-web
  namespace: salespot
  labels:
    app: salespot-web
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salespot-web
  template:
    metadata:
      labels:
        app: salespot-web
        version: v1
    spec:
      containers:
        - name: web
          image: salespot-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3000'
            - name: NEXT_PUBLIC_API_URL
              value: 'https://api.salespot.by'
            - name: NEXT_PUBLIC_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: salespot-secrets
                  key: SUPABASE_URL
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: salespot-secrets
                  key: SUPABASE_ANON_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: salespot-secrets
                  key: SENTRY_DSN
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
